GrumingProject/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GrumingProject.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Логин")]
        public string? UserName { get; set; }

        [Required]
        [UIHint("password")]
        [Display(Name = "Пароль")]
        public string? Password { get; set; }

        [Display(Name = "Запомнить меня?")]
        public bool RememberMe { get; set; }
    }
}

GrumingProject/Models/ViewComponents/SidebarViewComponent.cs
using GrumingProject.Domain;
using Microsoft.AspNetCore.Mvc;

namespace GrumingProject.Models.ViewComponents
{
	public class SidebarViewComponent : ViewComponent
	{
		private readonly DataManager dataManager;

		public SidebarViewComponent(DataManager dataManager)
		{
			this.dataManager = dataManager;
		}
		public Task<IViewComponentResult> InvokeAsync()
		{
			return Task.FromResult((IViewComponentResult)View("Default",dataManager?.ServiceItems?.GetServiceItems()));
		}
	}
}

GrumingProject/Areas/Admin/Controllers/HomeController.cs
using GrumingProject.Domain;
using Microsoft.AspNetCore.Mvc;


namespace GrumingProject.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class HomeController : Controller
	{
		private readonly DataManager dataManager;

		public HomeController(DataManager dataManager)
		{
			this.dataManager = dataManager;
		}

		public IActionResult Index()
		{
			return View(dataManager?.ServiceItems?.GetServiceItems());
		}
	}
}

GrumingProject/Areas/Admin/Controllers/ServiceItemsController.cs
using System;
using System.IO;
using GrumingProject.Controllers;
using GrumingProject.Domain;
using GrumingProject.Domain.Entities;
using GrumingProject.Service;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;


namespace GrumingProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ServiceItemsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        public ServiceItemsController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new ServiceItem() : dataManager?.ServiceItems?.GetServiceByItem(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(ServiceItem model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "img/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                dataManager?.ServiceItems?.SaveServiceItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager?.ServiceItems?.DeleteServiceItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

GrumingProject/Areas/Admin/Controllers/TextFieldsController.cs
using GrumingProject.Controllers;
using GrumingProject.Domain;
using GrumingProject.Domain.Entities;
using GrumingProject.Service;
using Microsoft.AspNetCore.Mvc;

namespace GrumingProject.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class TextFieldsController : Controller
	{
		private readonly DataManager dataManager;

		public TextFieldsController(DataManager dataManager)
		{
			this.dataManager = dataManager;
		}

		public IActionResult Edit(string codeWord)
		{
			var entity = dataManager?.TextFields?.GetTextFieldByCodeWord(codeWord);
			return View(entity);
		}
		[HttpPost]
		public IActionResult Edit(TextField model)
		{
			if (ModelState.IsValid)
			{
				dataManager?.TextFields?.SaveTextField(model);
				return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
			}
			return View(model);
		}
	}
}

GrumingProject/Controllers/AccountController.cs
using GrumingProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;


namespace GrumingProject.Controllers
{
	[Authorize]
	public class AccountController : Controller
	{
		private readonly UserManager<IdentityUser> userManager;
		private readonly SignInManager<IdentityUser> signInManager;

		public AccountController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
		{
			this.userManager = userManager;
			this.signInManager = signInManager;
		}
		[AllowAnonymous]
		public IActionResult Login(string returnUrl)
		{
			ViewBag.ReturnUrl = returnUrl;
			return View(new LoginViewModel());
		}
		[HttpPost]
		[AllowAnonymous]
		public async Task<IActionResult> Login(LoginViewModel model,string returnUrl)
		{
			if (ModelState.IsValid)
			{
				IdentityUser user = await userManager.FindByNameAsync(model.UserName);
				if (user != null)
				{
					await signInManager.SignOutAsync();
					Microsoft.AspNetCore.Identity.SignInResult result = await signInManager.PasswordSignInAsync(user, model.Password, model.RememberMe, false);
					if (result.Succeeded)
					{
						return Redirect(returnUrl ?? "/");
					}
				}
				ModelState.AddModelError(nameof(LoginViewModel.UserName), "Неверный логин и пароль");
			}
			return View(model);
		}

		[Authorize]
		public async Task<IActionResult> Logout()
		{
			await signInManager.SignOutAsync();
			return RedirectToAction("Index", "Home");
		}
	}
}

GrumingProject/Controllers/HomeController.cs
using GrumingProject.Domain;
using Microsoft.AspNetCore.Mvc;

namespace GrumingProject.Controllers
{
	public class HomeController : Controller
	{
		private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
		{
			return View(dataManager.TextFields.GetTextFieldByCodeWord("PageIndex"));
		}
        public IActionResult Contacts()
        {
            return View(dataManager.TextFields.GetTextFieldByCodeWord("PageContacts"));
        }
    }
}

GrumingProject/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;
using GrumingProject.Domain;

namespace GrumingProject.Controllers
{
	public class ServicesController : Controller
	{
		private readonly DataManager dataManager;

		public ServicesController(DataManager dataManager)
		{
			this.dataManager = dataManager;
		}

		public IActionResult Index(Guid id)
		{
			if(id != default)
			{
				return View("Show",dataManager.ServiceItems.GetServiceByItem(id));
			}
			ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageService");
			return View(dataManager.ServiceItems.GetServiceItems());
			
		}
	}
}

GrumingProject/Areas/Admin/Views/Home/Index.cshtml
@model IQueryable<ServiceItem>
@{
    string strTitle = "Панель администратора";
    ViewBag.Title = strTitle;
}

<div>
    <h2>@strTitle</h2>
    <div>
        <h3>Наши услуги</h3>
        <div class="div-box">
            <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="">Добавить услугу</a>
        </div>
        @if (Model.Any())
        {
            <div>
                @foreach (ServiceItem entity in Model)
                {
                    <div>
                        <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="@entity.Id">редактировать</a>
                        |
                        <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="ServiceItems" asp-action="Delete" method="post">
                            <input type="hidden" name="id" value="@entity.Id">
                            <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">удалить</a>
                        </form>
                        |
                        <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                            @($"{entity.Title}")
                        </a>
                    </div>
                }
            </div>
        }
    </div>
    <div class="div-box">
        <h3>Редактировать страницы сайта</h3>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageIndex">Главная</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageServices">Наши услуги</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageContacts">Контакты</a>
    </div>
    <div class="div-box">
        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
            <input type="submit" value="Выйти" />
        </form>
    </div>
</div>

GrumingProject/Areas/Admin/Views/ServiceItems/Edit.cshtml
@model ServiceItem
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="TitleImagePath" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Subtitle"></label>
                <input asp-for="Subtitle" />
                <span asp-validation-for="Subtitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="TitleImagePath"></label>
                <input type="file" name="titleImageFile" id="titleImageFile" />
                <div>
                    <img class="img-block" src="~/img/@Model.TitleImagePath" />
                </div>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>



<script>
    window.onload = function () {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>

GrumingProject/Areas/Admin/Views/TextFields/Edit.cshtml
@model TextField
@{
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="TextFields" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="CodeWord" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>



<script>
    window.onload = function () {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>

GrumingProject/Views/Home/Contacts.cshtml
@model TextField
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}
@*<div>
    @Html.Raw(Model.Text)
</div>*@
<div class="main-service">
    <h1 class="about-title">О себе</h1>
    <p>@Html.Raw(Model.Text)</p>
    <h2>Где нас найти</h2>
    <iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A890b735fd35b5c7a05d86a629506420593b801f4ca2ab715bef504956327a23c&amp;source=constructor" width="500" height="400" frameborder="0"></iframe>
</div>
<div class="sidebar-foto">
    <img src="/img/Фото автора.png" alt="">

</div>

GrumingProject/Views/Home/Index.cshtml
@*<div class="main-service">
    <h1 class="main-title">Стрижка животных</h1>
    <img class="main-img" src="/img/лев.jpg" alt="Услуга"><br>
    <p class="main-decription">Описание услуги</p>
</div>*@
@model TextField
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}
<div>
    @Html.Raw(Model.Text)
</div>

GrumingProject/Views/Services/Index.cshtml
@model IQueryable<ServiceItem>
@{
	TextField textField = ViewBag.TextField;

	ViewBag.Title = textField.MetaTitle;
	ViewBag.Description = textField.MetaDescription;
	ViewBag.Keywords = textField.MetaKeywords;
}

<div class="main-img">
	@if (Model.Any())
	{
		<ul class="big-image-list">
			@foreach (var entity in Model)
			{
				<li>
					<a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
						<img src="~/img/@entity.TitleImagePath" alt="" class="left" />
					</a>
					<h4>@entity.Title</h4>
					<p>@entity.Subtitle</p>
				</li>
			}

		</ul>
	}
</div>

GrumingProject/Views/Services/Show.cshtml
@model ServiceItem
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.Keywords = Model.MetaKeywords;
}

<div>
    <h2>
        @Model.Title
    </h2>
    <h2>
        @Model.Subtitle
    </h2>
    <div>
        <img class="img-block" src="~/img/@Model.TitleImagePath" />
    </div>
    <div>
        @Html.Raw(Model.Text)
    </div>
</div>

GrumingProject/Views/Shared/Components/Sidebar/Default.cshtml
@*<div class="sidebar">
    <ul>
        <h2 class="sidebar-title">Наши услуги</h2>
        <li>
            <h3 class="h3-main-text">Стрижка животных</h3>
            <img src="/img/лев.jpg" alt="">
        </li>
        <li>
            <h3 class="h3-main-text">Передержка животных</h3>
            <img src="/img/b53ee1c14ca8269668c62d1db1d5d846.jpg" alt="">
        </li>
        <li>
            <h3 class="h3-main-text">Вязка собак</h3>
            <img src="/img/вязка.jpg" alt="">
        </li>
    </ul>
</div>*@
@model IQueryable<ServiceItem>

@if (Model?.Any() == true)
{
    <ul>
        <h2 class="sidebar-title">Наши услуги</h2>
        @foreach(var entity in Model)
        {
            <li>
                <h3 class="h3-main-text">@entity.Title</h3>
                <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
					<img src="~/img/@entity.TitleImagePath" alt=""/>
                </a>
				<p>@entity.Subtitle</p>
            </li>
        }
    </ul>
}

 

GrumingProject/Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/style.css" asp-append-version="true">

GrumingProject/Views/Shared/FontsPartial.cshtml
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Caveat&display=swap" rel="stylesheet">

GrumingProject/Views/Shared/FooterPartial.cshtml
<footer class="footer">
    <div class="container">
        <div class="footer-content">
            <ul>
                <li><span class="copyright">Сайт создан&nbsp</span><a href="https://github.com/ErmakVitaliy" target="_blank">Ermak</a></li>
                <li>
                    <img src="/img/icons8-логотип-вконтакте.svg" alt="">
                    <a href="#">ВКонтакте</a>
                </li>
                <li>
                    <img src="/img/icons8-одноклассники.svg" alt="">
                    <a href="#">Одноклассники</a>
                </li>
                <li>
                    <img src="/img/icons8-телефон-64.png" alt="" width="48px">
                    <a href="tel:+79184323969">8 (918) 432-39-69</a>
                </li>
            </ul>
        </div>
    </div>
</footer>

GrumingProject/Views/Shared/HeaderPartial.cshtml
<header class="header">
    <div class="container">
        <div class="menu">
            <div class="title">
                <a href="/">@Config.CompanyName</a>
            </div>
            <ul class="nav">
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="">Наши услуги</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Contacts">Контакты</a>
                </li>
            </ul>
        </div>
    </div>
</header>

GrumingProject/Views/Shared/MainPartial.cshtml
            <div class="main-service">
                <h1 class="main-title">Стрижка животных</h1>
                <img class="main-img" src="/img/лев.jpg" alt="Услуга"><br>
                <p class="main-decription">Описание услуги</p>
            </div>
           
   

GrumingProject/Views/Shared/MetatagsPartial.cshtml
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
@if(ViewBag.Title != null)
{
	<title>@ViewBag.Title</title>
}
else
{
	<title>@Config.CompanyName</title>
}
@if(ViewBag.Description != null)
{
	<meta name="description" content="@ViewBag.Description"/>
}
@if (ViewBag.Keywords != null)
{
	<meta name="keywords" content="@ViewBag.Keywords" />
}

GrumingProject/Views/Shared/SidebarPartial.cshtml
@*<div class="sidebar">
    <ul>
        <h2 class="sidebar-title">Наши услуги</h2>
        <li>
            <h3 class="h3-main-text">Стрижка животных</h3>
            <img src="/img/лев.jpg" alt="">
        </li>
        <li>
            <h3 class="h3-main-text">Передержка животных</h3>
            <img src="/img/b53ee1c14ca8269668c62d1db1d5d846.jpg" alt="">
        </li>
        <li>
            <h3 class="h3-main-text">Вязка собак</h3>
            <img src="/img/вязка.jpg" alt="">
        </li>
    </ul>
</div>*@
<div class="sidebar">
    <cache>
        @(await Component.InvokeAsync<SidebarViewComponent>())
    </cache>
</div>

GrumingProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
   @await Html.PartialAsync("MetatagsPartial")
   @await Html.PartialAsync("FontsPartial")
   @await Html.PartialAsync("CssPartial")
    
</head>
<body> 
    <div class="wrapper">
        @await Html.PartialAsync("HeaderPartial")
        <main class="main">
            <div class="container">
                <div class="main-content">
                    @RenderBody();
                  @await Html.PartialAsync("SidebarPartial")
                </div>
            </div>
        </main>
        @await Html.PartialAsync("FooterPartial") 
    </div>
    @await Html.PartialAsync("ScriptsPartial")
</body>
</html>